LTI-232: updated documentation for tenant_settings.md
bigbluebutton/bbb-lti-broker pull request #193
Opened 2024-02-20 21:04 UTC by ahmed-abdou1

Updated documentation for tenant_settings.md to include hide_build_tag setting. Now the documentation for the hide_build_tag specifies its description as "Whether or not to hide the build tag feature. The default is true.".

2024-02-20 21:14 UTC, Mariam05 requested changes

2024-02-20 21:14 UTC, Mariam05 commented on tenant_settings.md
> +| hide_build_tag | Whether or not to hide the build tag feature. The default is true. |
can you change the description to be: `Whether or not to hide the build tag. The default is false. `
(by default, if this setting is not set to true, then we show the build tag)

2024-02-29 18:37 UTC, jfederico approved these changes

2024-02-29 18:39 UTC, Mariam05 approved these changes

2024-02-29 19:29 UTC, merged